spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        ## Product Service Route
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product

        ## Order Service Route
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order

        ## Discovery Service Route
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        ## Discovery Server Static Resources Route
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          - gateway: TRACE
          - gateway:
              route:
                RouteDefinitionLocator: INFO
